Feat: add deploy scripts
makerdao/dss-emergency-spells pull request #9
Opened 2024-11-24 22:11 UTC by amusingaxl

2024-11-26 00:11 UTC, Farnoosh85 requested changes
information on data protection

2024-11-26 00:19 UTC, Farnoosh85 requested changes

2024-11-26 00:19 UTC, Farnoosh85 commented on README.md
> +| `ETH-A`     | `0x3a03F35ba1F5e015a288feD50cEB5342d4989E85` |
Organization validation

2024-11-26 00:27 UTC, oddaf commented on script/MultiClipBreakerDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```

Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/MultiLineWipeDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/MultiOsmStopDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```

Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SingleClipBreakerDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SingleDdmDisableDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SingleLineWipeDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SingleLitePsmHaltDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SingleOsmStopDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:27 UTC, oddaf commented on script/SplitterStopDeploy.s.sol
> +import {MCD, DssInstance} from "dss-test/MCD.sol";
```suggestion
```
Unused imports

2024-11-26 00:51 UTC, oddaf commented
All deployed contracts in the readme were:
a. Verified on Etherscan
b. Contain the correct collateral
c. Bytecode matches the version in the repository (commit f9308604f731ab180f6eb10d463b3edeb6a9a127, used in the Chainsecurity audit).

2024-11-28 00:15 UTC, oddaf approved these changes

2024-11-29 14:21 UTC, 0xp3th1um approved these changes
lgtm
The deployed contracts and their bytecode on Etherscan were also verified against commit https://github.com/makerdao/dss-emergency-spells/commit/f9308604f731ab180f6eb10d463b3edeb6a9a127 (Chainsecurity audit)

2024-11-29 15:52 UTC, merged